SELECT * FROM CUSTOMERS
WHERE SALARY LIKE '200%';

-- SELECT * FROM CUSTOMERS
-- WHERE SALARY LIKE '%00';

-- SELECT * FROM CUSTOMERS
-- WHERE ADDRESS LIKE '%I';

-- SELECT * FROM CUSTOMERS
-- WHERE ADDRESS LIKE '_OT_';

-- SELECT * FROM CUSTOMERS
-- WHERE AGE LIKE '2_';

-- SELECT * FROM CUSTOMERS
-- WHERE NAME LIKE 'H____K';