SELECT 
    *
FROM
    CUSTOMERS
ORDER BY NAME DESC;

-- OWN ORDER OF PREFERENCE
-- SELECT 
--     *
-- FROM
--     CUSTOMERS
-- ORDER BY (CASE ADDRESS
--     WHEN 'DELHI' THEN 1
--     WHEN 'BHOPAL' THEN 2
--     WHEN 'KOTA' THEN 3
--     WHEN 'MUMBAI' THEN 4
--     WHEN 'INDORE' THEN 5
--     ELSE 100
-- END) ASC , ADDRESS DESC;