SELECT 
    ID, NAME, AMOUNT, DATE
FROM
    CUSTOMERS c
        LEFT JOIN
    ORDERS o ON c.ID = o.CUSTOMER_ID 
UNION SELECT 
    ID, NAME, AMOUNT, DATE
FROM
    CUSTOMERS c
        RIGHT JOIN
    ORDERS o ON c.ID = o.CUSTOMER_ID;