SELECT 
    C.ID, C.NAME, C.AGE, O.AMOUNT
FROM
    CUSTOMERS AS C,
    ORDERS AS O
WHERE
    C.ID = O.CUSTOMER_ID;

-- -- COLUMN ALIAS
-- SELECT 
--     ID AS CUSTOMER_ID, NAME AS CUSTOMER_NAME
-- FROM
--     CUSTOMERS
-- WHERE
--     SALARY IS NOT NULL;