SELECT * 
FROM CUSTOMERS 
-- SELECT ALL CUSTOMERS WHOSE ID IN (4,5,7)
WHERE ID IN (SELECT ID 
	FROM CUSTOMERS 
	WHERE SALARY > 4500) ;
    
-- -- INSERT
-- INSERT INTO NEW_TABLE
--    SELECT * FROM OLD_TABLE 
--    WHERE COLUMN_NAME IN (SELECT COLUMN_NAME 
--    FROM OLD_TABLE) ;

-- -- UPDATE
-- UPDATE OLD_TABLE
--    SET COLUMN_NAME =  VALUE
--    WHERE COLUMN_NAME IN (SELECT COLUMN_NAME FROM NEW_TABLE
--       WHERE CONDITION );

-- -- DELETE
-- DELETE FROM OLD_TABLE
--    WHERE COLUMN_NAME IN (SELECT COLUMN_NAME FROM NEW_TABLE
--       WHERE CONDITION );